name: clustenv_test
channels:
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - ca-certificates=2024.9.24=haa95532_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py38haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h2bbff1b_1
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libtiff=4.5.1=hd77b12b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.5.2=py38haa95532_0
  - matplotlib-base=3.5.2=py38hd77b12b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.0.10=py38h2bbff1b_0
  - openssl=3.0.12=h2bbff1b_0
  - packaging=23.1=py38haa95532_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pillow=10.0.1=py38h045eedc_0
  - pip=23.3=py38haa95532_0
  - ply=3.11=py38_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - python=3.8.18=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - qt-main=5.15.2=h19c9488_10
  - scipy=1.8.1=py38h4990095_2
  - seaborn=0.13.2=py38haa95532_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - setuptools=68.0.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - statsmodels=0.14.0=py38h9128911_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=py38haa95532_0
  - tornado=6.3.3=py38h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py38haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - absl-py==2.0.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - attrs==24.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - cython==3.0.6
    - dcor==0.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docopt==0.6.2
    - executing==2.1.0
    - fastjsonschema==2.20.0
    - fdasrsf==2.5.2
    - findiff==0.10.0
    - flatbuffers==23.5.26
    - gast==0.4.0
    - grpcio==1.59.3
    - gviz-api==1.10.0
    - h5py==3.10.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.4.5
    - ipython==8.12.3
    - jedi==0.19.2
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - lazy-loader==0.3
    - libclang==16.0.6
    - littleutils==0.2.2
    - llvmlite==0.41.1
    - lxml==5.2.2
    - markdown==3.5.1
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - mplcursors==0.5.2
    - mpmath==1.3.0
    - multimethod==1.10
    - natsort==8.4.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - numba==0.58.1
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - outdated==0.2.2
    - pandas==2.0.3
    - pandas-flavor==0.6.0
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pickleshare==0.7.5
    - pingouin==0.5.3
    - pipreqs==0.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.48
    - protobuf==3.19.6
    - pure-eval==0.2.3
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pygments==2.18.0
    - python-docx==1.1.2
    - pywin32==308
    - pyzmq==26.2.0
    - rdata==0.9
    - referencing==0.35.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rpds-py==0.20.1
    - rsa==4.9
    - scikit-datasets==0.2.4
    - scikit-fda==0.9
    - scikit-learn==1.3.2
    - scikit-posthocs==0.8.0
    - soupsieve==2.6
    - spm1d==0.4.20
    - stack-data==0.6.3
    - stumpy==1.12.0
    - sympy==1.12
    - tabulate==0.9.0
    - termcolor==2.3.0
    - threadpoolctl==3.2.0
    - tinycss2==1.4.0
    - tqdm==4.66.1
    - traitlets==5.14.3
    - typing-extensions==4.12.2
    - tzdata==2023.3
    - urllib3==2.1.0
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - werkzeug==3.0.1
    - wrapt==1.16.0
    - xarray==2023.1.0
    - yarg==0.1.9
    - yellowbrick==1.5
    - zipp==3.17.0
prefix: C:\Users\arr43\Anaconda3\envs\PhDEnv2024please
